# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20170416_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='activation_code',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='code_expires',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
